export const trabajadores = [
  {
    rut: "159334244",
    nombre: "Juan",
    apellido: "Pérez",
    telefono: "60577390",
    correo: "juan.perez@granjero.cl",
    direccion: "Av. Los Robles 125, Santiago",
    rol: "BODEGA",
    tienda: "Bodega Central",
    estado: "Activo",
  },
  {
    rut: "198765432",
    nombre: "Ana",
    apellido: "Soto",
    telefono: "987654321",
    correo: "ana.soto@granjero.cl",
    direccion: "Calle Bilbao 45, Concepción",
    rol: "VENDEDOR",
    tienda: "Bilbao",
    estado: "Activo",
  },
  {
    rut: "205551234",
    nombre: "Carlos",
    apellido: "Muñoz",
    telefono: "912345678",
    correo: "carlos.munoz@granjero.cl",
    direccion: "Pasaje Providencia 78, Santiago",
    rol: "ADMINISTRADOR",
    tienda: "La Concepción",
    estado: "Inactivo",
  },
];
